Fix reference to mk-ca-bundle-pl
In curl/curl#8625, `mk-ca-bundle.pl` was moved from `lib/` to `scripts/`. The installer today fails with the following error:
```
==> make install -C scripts
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - lib/mk-ca-bundle.pl
```

This PR fixes the path so the build works with the latest checkout of `curl`.