Prefer livecheck to appcast
Updates remote version checks to use `livecheck` instead of `appcast`:

    Error: Cask 'cf-terraforming' definition is invalid: 'appcast' stanza
    failed with: Calling the `appcast` stanza is deprecated! Use the
    `livecheck` stanza instead.

https://docs.brew.sh/Brew-Livecheck